# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.synced_folder "../../setup", "/setup"
  config.vm.synced_folder "../../projects", "/projects"

  config.vm.provision "shell", inline: <<-SHELL
    source /setup/init.bash
    source /setup/modules/utils.bash
    source /setup/modules/git.bash
    source /setup/modules/apache.bash
    source /setup/modules/php.bash
    source /setup/modules/mysql.bash
    source /setup/modules/node.bash
    set_hostname php
    install_git "Amine Ben hammou" webneat@gmail.com vim
    install_apache rewrite
    install_php phpunit codeception
    install_mysql
    install_node "yarn bower gulp"
  SHELL
end