## Git Aliases
alias ga='git add'
alias gb='git branch'
alias gc='git commit -m'
alias gf='git fetch'
alias gl='git log'
alias gm='git merge'
alias gr='git rebase'
alias gs='git status'
alias gp='git push origin'
alias gpl='git pull origin'
alias gco='git checkout'
alias gcp='git cherry-pick'
